/* Cronômetro — ferramentas exclusivas do ambiente Beta */
(() => {
  'use strict';
  const BETA_RELEASE='0.8.9-beta.22';
  const PROD_DB='cronometro_local_v1';
  const BETA_DB='cronometro_beta_v1';
  const STORES=['models','sessions','state'];

  function openDb(name){return new Promise((resolve,reject)=>{const r=indexedDB.open(name,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('models'))d.createObjectStore('models',{keyPath:'id'});if(!d.objectStoreNames.contains('sessions'))d.createObjectStore('sessions',{keyPath:'id'});if(!d.objectStoreNames.contains('state'))d.createObjectStore('state',{keyPath:'key'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error(`Falha ao abrir ${name}`));r.onblocked=()=>reject(new Error(`Banco ${name} bloqueado`))})}
  function req(r){return new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async function readStore(db,name){if(!db.objectStoreNames.contains(name))return [];return req(db.transaction(name,'readonly').objectStore(name).getAll())}
  async function replaceStore(db,name,rows){if(!db.objectStoreNames.contains(name))return;await new Promise((resolve,reject)=>{const tx=db.transaction(name,'readwrite'),store=tx.objectStore(name);store.clear();for(const row of rows||[])store.put(row);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Transação cancelada'))})}
  async function copyOfficialToBeta(){const source=await openDb(PROD_DB),target=await openDb(BETA_DB);try{const snap={};for(const store of STORES)snap[store]=await readStore(source,store);for(const store of STORES)await replaceStore(target,store,snap[store]);try{localStorage.setItem('cronometro-beta-copied-at',new Date().toISOString())}catch(_){}return {models:snap.models?.length||0,sessions:(snap.sessions||[]).filter(s=>s?.status==='saved').length,state:snap.state?.length||0}}finally{source.close();target.close()}}
  async function clearBetaOnly(){const db=await openDb(BETA_DB);try{for(const store of STORES)await replaceStore(db,store,[])}finally{db.close()}try{Object.keys(localStorage).filter(k=>k.startsWith('cronometro-beta-')).forEach(k=>localStorage.removeItem(k))}catch(_){}}
  async function loadDemoPayload(){const response=await fetch('./beta-demo-data.json',{cache:'no-store'});if(!response.ok)throw new Error('Dados fictícios da Beta indisponíveis');return response.json()}
  function demoTimer(template,sessionId,index,startedAt,durationMin){const duration=Math.max(0,Number(durationMin)||0)*60000,endedAt=startedAt+duration;return {id:`${sessionId}-timer-${index+1}`,templateId:template.id,name:template.name,order:template.order,isAdhoc:false,isRemoved:false,intervals:duration>0?[{id:`${sessionId}-interval-${index+1}`,startedAt,endedAt,origin:'beta-demo'}]:[],ignoredIntervals:[],correctedDurationMs:null,measurementStatus:duration>0?'measured':'notNeeded',marker:template.marker||null,__endedAt:endedAt}}
  function materializeDemoSession(spec,models,clients,baseNow){const model=models.find(m=>m.id===spec.modelId)||models[0],client=clients.find(c=>c.id===spec.clientId)||null;if(!model)return null;const d=new Date(baseNow);d.setHours(Number.isFinite(spec.hour)?spec.hour:10,Number.isFinite(spec.minute)?spec.minute:0,0,0);d.setDate(d.getDate()-Math.max(0,Number(spec.daysAgo)||0));const openedAt=d.getTime();let cursor=openedAt+120000;const durations=Array.isArray(spec.durationsMin)?spec.durationsMin:[];const timers=(model.timers||[]).filter(t=>!t.removedAt).sort((a,b)=>a.order-b.order).map((template,index)=>{const timer=demoTimer(template,spec.id,index,cursor,durations[index]??0);cursor=timer.__endedAt+20000;delete timer.__endedAt;return timer});const first=timers.find(t=>t.intervals?.length)?.intervals?.[0]?.startedAt||openedAt;const savedAt=Math.max(first,cursor-20000);return {id:spec.id,modelId:model.id,modelNameSnapshot:model.name,areaId:'principal',title:client?.name||'Cliente de demonstração',manualTitle:false,note:String(spec.appointmentNote||''),appointmentNote:String(spec.appointmentNote||''),clientNote:String(spec.clientNote||''),clientId:client?.id||null,clientNameSnapshot:client?.name||'',openedAt,firstTimerStartedAt:first,savedAt,originalRecordedAt:first,restoredAt:null,deletedAt:null,status:'saved',isNoMeasurement:false,globalPaused:false,pauseIntervals:[],pausedActiveTimerIds:[],customized:false,timers,clientMode:true}}
  async function installDemoData({force=false}={}){const payload=await loadDemoPayload(),target=await openDb(BETA_DB);try{const models=await readStore(target,'models'),sessions=await readStore(target,'sessions'),state=await readStore(target,'state');const saved=sessions.filter(s=>s?.status==='saved'&&!s.deletedAt),hasDemo=saved.some(s=>/^demo-s\d+$/.test(String(s.id||'')));if(!force&&saved.length&&!hasDemo)return {changed:false,reason:'real-data'};if(force){for(const store of STORES)await replaceStore(target,store,[])}
      const currentModels=force?[]:models,currentSessions=force?[]:sessions,currentState=force?[]:state;
      const modelMap=new Map(currentModels.map(x=>[x.id,x]));for(const model of payload.models||[])if(!modelMap.has(model.id)){modelMap.set(model.id,model);await req(target.transaction('models','readwrite').objectStore('models').put(model))}
      const settingsRow=currentState.find(x=>x.key==='settings');const existingSettings=settingsRow?.value&&typeof settingsRow.value==='object'?settingsRow.value:{};const seedSettings=payload.settings&&typeof payload.settings==='object'?payload.settings:{};const clients=[...(Array.isArray(existingSettings.clients)?existingSettings.clients:[])];const byClient=new Map(clients.map(x=>[x.id,x]));for(const seed of seedSettings.clients||[]){const current=byClient.get(seed.id);if(!current){clients.push(seed);byClient.set(seed.id,seed)}else if(String(seed.id).startsWith('client-demo-'))Object.assign(current,seed)}
      const settings={...seedSettings,...existingSettings,areas:[{id:'principal',name:'Atendimentos',type:'clients'}],activeAreaId:'principal',clients};await req(target.transaction('state','readwrite').objectStore('state').put({key:'settings',value:settings}));
      const existingIds=new Set(currentSessions.map(x=>String(x.id||''))),baseNow=Date.now(),modelList=[...modelMap.values()];let added=0;for(const spec of payload.demo?.sessions||[]){if(existingIds.has(String(spec.id)))continue;const session=materializeDemoSession(spec,modelList,clients,baseNow);if(!session)continue;await req(target.transaction('sessions','readwrite').objectStore('sessions').put(session));existingIds.add(String(session.id));added++}
      await req(target.transaction('state','readwrite').objectStore('state').put({key:'beta-demo-dataset',value:{version:1,count:(payload.demo?.sessions||[]).length,updatedAt:Date.now()}}));return {changed:force||added>0,added,total:(payload.demo?.sessions||[]).length}
    }finally{target.close()}}
  async function ensureDemoData(){try{const result=await installDemoData();if(result.changed)location.reload()}catch(error){console.warn('Não foi possível preparar os dados fictícios da Beta.',error)}}

  function style(){if(document.getElementById('cronometroBetaStyle'))return;const el=document.createElement('style');el.id='cronometroBetaStyle';el.textContent=`
    #cronometroBetaBadge{position:fixed;top:max(8px,env(safe-area-inset-top));right:10px;z-index:2147482500;padding:5px 8px;border-radius:999px;background:#ff9500;color:#fff;font:800 9px/1 -apple-system,BlinkMacSystemFont,"SF Pro Text",sans-serif;letter-spacing:.02em;box-shadow:0 3px 12px rgba(0,0,0,.14);pointer-events:none}
    .cronometro-beta-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:12px 0}.cronometro-beta-actions button{appearance:none;border:0;border-radius:11px;padding:10px 8px;font:650 11px/1.15 inherit;background:#111114;color:#fff}.cronometro-beta-actions button:last-child{background:#e5e5ea;color:#1c1c1e}.cronometro-beta-actions .wide{grid-column:1/-1;background:#007aff;color:#fff}
    @media(prefers-color-scheme:dark){.cronometro-beta-actions button{background:#f2f2f4;color:#111114}.cronometro-beta-actions button:last-child{background:#2c2c2e;color:#f2f2f4}}
  `;document.head.appendChild(el)}
  function badge(){style();let b=document.getElementById('cronometroBetaBadge');if(!b){b=document.createElement('div');b.id='cronometroBetaBadge';document.body.appendChild(b)}b.textContent=BETA_RELEASE;return true}
  function bindActions(root){root.querySelector('#cronometroBetaDemo').onclick=async e=>{if(!confirm('Substituir somente os dados da Beta por 50 atendimentos fictícios distribuídos em cerca de seis meses?'))return;const b=e.currentTarget;b.disabled=true;b.textContent='Preparando…';try{await installDemoData({force:true});location.reload()}catch(error){console.error(error);b.disabled=false;b.textContent='Carregar 50 atendimentos fictícios';alert('Não foi possível carregar os dados fictícios da Beta.')}};root.querySelector('#cronometroBetaCopy').onclick=async e=>{if(!confirm('Substituir os dados atuais da Beta por uma cópia dos dados do app Oficial? O Oficial não será alterado.'))return;const b=e.currentTarget;b.disabled=true;b.textContent='Copiando…';try{const x=await copyOfficialToBeta();alert(`Cópia concluída: ${x.sessions} registros e ${x.models} modelos. O app Oficial permaneceu intacto.`);location.reload()}catch(error){console.error(error);b.disabled=false;b.textContent='Tentar novamente';alert('Não foi possível copiar os dados para a Beta. Nenhum dado do Oficial foi alterado.')}};
    root.querySelector('#cronometroBetaClear').onclick=async e=>{if(!confirm('Apagar somente os dados da Beta? Seus dados do app Oficial permanecerão intactos.'))return;const b=e.currentTarget;b.disabled=true;b.textContent='Limpando…';try{await clearBetaOnly();location.reload()}catch(error){console.error(error);b.disabled=false;b.textContent='Tentar novamente';alert('Não foi possível limpar a Beta. O Oficial não foi alterado.')}};}
  function settingsTools(){style();if(document.getElementById('cronometroBetaTools'))return false;const settings=document.querySelector('.settings-content');if(!settings)return false;const section=document.createElement('section');section.id='cronometroBetaTools';section.className='settings-section';section.innerHTML=`<h3 class="section-label">Ferramentas da Beta</h3><div class="settings-card"><div class="cronometro-beta-actions"><button type="button" id="cronometroBetaDemo" class="wide">Carregar 50 atendimentos fictícios</button><button type="button" id="cronometroBetaCopy">Copiar dados do Oficial</button><button type="button" id="cronometroBetaClear">Limpar Beta</button></div></div>`;settings.appendChild(section);bindActions(section);return true}
  function markVersion(){if(document.title!=='Cronômetro Beta')document.title='Cronômetro Beta';try{if(globalThis.APP_META?.version!==BETA_RELEASE)globalThis.APP_META=Object.freeze({...globalThis.APP_META,version:BETA_RELEASE})}catch(_){}document.querySelectorAll('#app-version-badge').forEach(el=>{if(el.textContent!==BETA_RELEASE)el.textContent=BETA_RELEASE})}
  function apply(){badge();markVersion();settingsTools()}

  apply();
  ensureDemoData();
  document.addEventListener('DOMContentLoaded',apply,{once:true});
  [60,250,800,1800].forEach(ms=>setTimeout(apply,ms));

  /* Observa somente a raiz do app. Durante o patch o observer fica desconectado,
     evitando o ciclo MutationObserver -> patch -> MutationObserver. */
  const root=document.getElementById('app');
  if(root){
    const observer=new MutationObserver(()=>{
      observer.disconnect();
      try{apply()}finally{observer.observe(root,{childList:true,subtree:true})}
    });
    observer.observe(root,{childList:true,subtree:true});
  }
})();
